### ISSUE TITLE
Consegna 2: Filtrare

### ISSUE THREAD

**Issue by saniales** [LesterCamp234/HTTP-server#4]
Vorrei un endpoint che agisca sugli stessi file dell'altro endpoint, ma fatto in questo modo

GET /products?min_rating=1&max_rating=5

che mi restituisca (di tutti i file) l'elenco che soddisfi i filtri di cui sopra

notare che se non metto nulla il default è minimo 0 massimo 5

**Comment by LesterCamp234** [comment]
La password, a sto punto, la posso anche togliere? Inoltre, per "/products", devo controllare se l'utente è in quella pagina per fare l'elenco?
