### ISSUE TITLE
Consegna 3: Modalità API JSON

### ISSUE THREAD

**Issue by saniales** [LesterCamp234/HTTP-server#5]
Questa consegna richiede la manipolazione degli header di risposta e la verifica degli header di richiesta:

- Se l'header "Content-type" della richiesta è diverso da application/json rispondere con errore HTTP 406 (Not Acceptable)
- Se l'header "Accept" della richiesta è "text/html" fornire la pagina HTML come gia è implementato
- Se l'header "Accept" della richiesta è "application/json" occorre fornire la risposta come JSON (va bene l'output di json.Marshal di quello che deve uscire)

Si noti che in ogni caso l'header "Content-type" della risposta deve essere impostato al valore che si trova in "Accept" nella richiesta.
Se la richiesta non è valida invece il "Content-type" della risposta deve essere impostato su "text/plain" e la risposta deve essere vuota (lo status va messo però)

**Comment by LesterCamp234** [comment]
Se l'accept della richiesta fosse "*/*", cosa devo fare?

**Comment by LesterCamp234** [comment]
Ho finito di fare l'esercizio, ma non sono molto sicuro se effettivamente ho fatto come voleva, per cui può dare un'occhiata al P.R #9?

**Comment by saniales** [comment]
Rispondi con un error message

```
Unsupported mime type in "Accept" header
```

**Comment by LesterCamp234** [comment]
L'ho aggiunto nel P.R
