### ISSUE TITLE
Errori su "FIltrare"

### ISSUE THREAD

**Issue by saniales** [LesterCamp234/HTTP-server#7]
https://github.com/LesterCamp234/HTTP-server/blob/fb0a177b172a6c86f6ce4ff47520fa2e988010ed/main.go#L26

voglio /products, non /

**Comment by LesterCamp234** [comment]
Avevo fatto che controllavo se era presente "/product" nel URL con "if r.URL.Path == "/product"", ma l'ho cambiato facendo un altro http.HandleFunc

**Comment by LesterCamp234** [comment]
#8
